### ISSUE TITLE
Comparisons of fractions are only valid when referring to the same sized whole

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/fraction-matcher#101]
We should revise the sizes of the figures being matched in Fraction Matcher so that they are equal in area. This is a point that has been brought up many times both internally and externally, so when we have some time to devote to it, we'd like to rescale the images so that their areas are the same. 

----- phethelp email -----

To whom it may concern,

I am new to using the PHET and am excited to have begun exploring the quality apps presented therein. I am hoping to use these in supporting elementary learners and teachers of mathematics in our district.

I found content, however, in one app: Fraction Matcher, that raises concern with regard to mathematical accuracy. Namely, recognizing that comparisons of fractions are only valid when referring to the same sized whole. I appreciate that care was demonstrated in using the language of “matching” fractions to describe the task, but (in my humble opinion) fraction equivalence is at the heart of this standard and cluster; not “matching” fractions.

Please see in the screenshot below that although both of the shaded regions of each shape could be represented with the same fraction, the fractional regions of the two shapes are NOT equivalent. Please consider revising the instances of comparisons involving shaded regions of shapes such that they are equal in size/area (e.g. consistent with CCSSM.2.G.A.3 – Recognize that equal shares of identical wholes need not have the same shape).

![image003](https://user-images.githubusercontent.com/7852916/28231228-9a6095ee-68a7-11e7-87f7-3fa65dce35d4.png)

Thank you again for creating and publishing these web-based apps!

Best regards,
Michael

**Comment by ariel-phet** [comment]
@samreid no need to devote any dev time to this at the moment, but when you get a chance, could you give an estimate as to what this would take?

I would imagine a straightforward approach would be something like this:

1. Pick a "base shape" - I am guessing the circle would be the most natural.
2. Choose the size of the base shape (potentially scale the circle up slightly)
3. Determine the total area of the base shape
4. Choose a scale factor for all other shapes such that there total area matches the base shape (for instance, right now the square would need to be scaled down). If the circle has a radius `r`, the square should have a side length of `sqrt(Pi)*r`
5. For other shapes, I am sure we could also define the exact mathematical relationship

**Comment by samreid** [comment]
I see 13 shape types in Pattern.js.  I'm also noticing that this is predominantly MLL code from when our quality standards were lower, so that will lead to increased time to make changes and we will likely find other problems while we are working on this.

There are 2 ways we could approach this.
1. Redesign the code so that it is "area aware" and automatically scales to have the right dimension so that areas are commensurate
2. Manually compute areas and compute scale factors

I think (2) will be the best way to proceed since the complexity of (1) doesn't seem warranted.

If it was as easy as computing the size of each shape and dividing by the area of the circle this would probably take 15-30 minutes per shape.  However, I do not know how the shapes deal with sizes as a function of denominator--we may (probably?) need to do this computation once per denominator.  Depending on how things go, it may end up requiring changes to the overall layout of the toolbox OR changing the code so that things change size when they pop out of the toolbox.  Either of these changes would be somewhat complex.  For instance, here are some shapes in a level I saw:
![image](https://user-images.githubusercontent.com/679486/28236504-fe91ef30-68e4-11e7-9062-bf5b32334900.png)

These would need to be normalized.

I guess I'll leave these as initial notes, but it seems like I should look into this further to search for issues with the proposal and better estimates.

**Comment by samreid** [comment]
@ariel-phet can you review my notes and let me know if you'd like me to investigate further (and if so, at what priority?)

**Comment by ariel-phet** [comment]
@samreid @amanda-phet 

I believe the rules/logic of the game are such that when there are two shapes present in a single cell they are always representing a fraction greater than 1. Thus a single shape will never match with two shapes. I suppose it is possible that when comparing a single shape with a double shape the single shape could actually have larger area if we keep things as now, but I doubt people will have an issue with this since it would be tough to judge, and the complaints are about equivalence.

So, @samreid I think it is fine if the small circles (double shape) are not the same size as a single shape. Thus comparisons of all double shapes would still be valid. 

Especially for younger students (on the easier levels), having the large easy to count divisions in single shapes is preferable and outweighs other concerns. 

@samreid doesn't that simplify things a bit? We definitely do not want things to change size when moved from the toolbox, since that conflates too many ideas.

**Comment by samreid** [comment]
That will remove one complicating factor--my other concern was about whether shapes with different denominators would need to be scaled differently (or whether it is already scaled proportionately).  Then I remembered not all shapes support all denominators:

```js
      //rules if shape_type can be used for denominator d
      var map = {
        PIES: true,
        HORIZONTAL_BARS: d < 9,
        VERTICAL_BARS: d < 9,
        PLUSES: d === 6,
        GRID: d === 4 || d === 9,
        PYRAMID: d === 1 || d === 4 || d === 9,
        TETRIS: d === 4,
        FLOWER: d === 6,
        LETTER_L_SHAPES: d % 2 === 0,
        INTERLEAVED_L_SHAPES: d === 2 || d === 4,
        RING_OF_HEXAGONS: d === 7,
        NINJA_STAR: d === 8
      };
```
So at worst, we will have to apply scaling for pies, bars and 17 or so other shapes.  At 15-30 minutes per shape this could work out to 5-10 hours or so, some (most?) of which could be done by a designer.

If you decide to delegate this to a designer, rather than asking the designer to compute scale factors for all shapes at once, it would be better to have them do 1 or 2 kinds of shapes then have the programmer implement the changes to make sure everything works out smoothly.  Then if everything is working out nicely, we can do the rest.

**Comment by ariel-phet** [comment]
@amanda-phet considering @samreid comments above, it might be useful to have you do some illustrator mockups so we can decide on the appropriate "base area" for single and double shapes, and then compute the scale factors. 

My suggestion would be mockup up several shapes at first, especially any that you think might be problematic, and then follow @samreid advice of trying a few in a dev version, making sure all looks good, and then moving on to doing scale factors for all.

**Comment by ariel-phet** [comment]
@amanda-phet also, considering the nature of the shapes, my gut tells me again that the circle would be the best staring point, and all scale factors could be exactly computed in terms of the radius of the circle.

**Comment by amanda-phet** [comment]
That sounds good to me. When do you think we should spend time on this? I am under the impression that this sim won't be revisited for a while, but let me know when you'd like me to work on these mockups.

**Comment by ariel-phet** [comment]
@amanda-phet I think it would be possible to revisit the sim as part of a11y/iO work. MK has been working through some older sims, and he is currently reviewing a more complex sim (molecule polarity), so this one my be a good opportunity to bring up to standard as well as make some changes. It also presents some slightly more interesting keyboard nav challenges. So I think it is a bit up to you...if it is a priority to you, I think we can get it done sooner than later (but probably not with @samreid time)

And quick reminder - please always reassign me to ensure a reply :)!

**Comment by zepumph** [comment]
I worked with @samreid to get a way to test these shapes easier. We came up with the `?testDenominator=d` query parameter that will outfit Level 1 on the fraction screen, where d is equal to the denominator of your choosing, between 2 and 9.

This query parameter will populate the first screen with only shapes, and will have fractions from 1/d to 6/d (two shapes each).

@samreid please take a look and provide feedback. I think it will help us easily compare the changes that we will make once @amanda-phet has some scales to implement.

**Comment by samreid** [comment]
Looks great, thanks!  I think the next step will be to get shape widths from @amanda-phet

**Comment by zepumph** [comment]
Sounds good.

**Comment by jonathanolson** [comment]
I was looking into this, and I'm a bit confused why there would be a per-shape cost here. Use `Shape.getArea()` on the outline shape, and scale them so they all match?

I'll be available to help with this.

**Comment by amanda-phet** [comment]
This is being addressed in the latest version of the sim, so I think it can be closed.
