### ISSUE TITLE
Question: Identical representations

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/fraction-matcher#76]
Is it ok that sometimes a level will offer representations to match that are exactly the same except for the colour?

e.g. The red and blue halves on the balances, and the L-shaped pieces:
![screen shot 2014-07-19 at 3 57 30 pm](https://cloud.githubusercontent.com/assets/4682895/3636521/924ce888-0fc9-11e4-9a5f-5331ca120ea3.png)

**Comment by jonathanolson** [comment]
@amanda-phet and @ariel-phet this seems like something fixable, but it might add a lot of tricky constraints on level generation (particularly the 1st screen 1st level, which is limited enough that duplicates with different colors are highly likely). Thoughts?

**Comment by ariel-phet** [comment]
I think this issue is rare enough, and only happening on the lower levels, that we can go ahead and close it.

Additionally, the sim has been our for years with no complaints. Equivalent is equivalent, so a few matching representations here and there is just not a big deal, and I believe they are almost always a different color if they are matching representations.

Closing
