### ISSUE TITLE
Evaluate for S2015R

### ISSUE THREAD

**Issue by samreid** [phetsims/fraction-matcher#90]
Evaluate for i18n, low-hanging fruit for quick fixes, etc. @ariel-phet requested @samreid to come up with an estimate.

**Comment by samreid** [comment]
Here is stringTest=long:

![image](https://cloud.githubusercontent.com/assets/679486/13511459/d45f0e16-e152-11e5-813a-01626c9b35e0.png)

**Comment by samreid** [comment]
Here's the stringTest = double:

![image](https://cloud.githubusercontent.com/assets/679486/13511479/eb7dc092-e152-11e5-9b3c-4e3e60a53e55.png)

**Comment by samreid** [comment]
I standardized the string keys in the above commit.  Why is +1 duplicating?

![image](https://cloud.githubusercontent.com/assets/679486/13511905/9bb4eade-e154-11e5-807a-0888f1823fdb.png)

**Comment by samreid** [comment]
This is using SCENERY_PHET/FaceWithPointsNode.pattern_0sign_1points.

Here's the entry from scenery-phet:

```js
  "FaceWithPointsNode.pattern_0sign_1points": {
    "value": "{0}{1}"
  },
```

@jbphet added this code to FaceWithPointsNode, can you comment why this is internationalized?

@ariel-phet should we un-internationalize FaceWithPointsNode and just show +1, -2, etc. without making it internationalized?

Otherwise, the stringTest=double seems OK and the long test is not too crazy, @ariel-phet can you pull and test and let me know if you want any maxWidths set before we proceed to release testing?

**Comment by ariel-phet** [comment]
@samreid a few things...

- the "mixed numbers" level selection screen the title "Choose your level! Mixed Numbers" does not pass ?stringtest=double. Max width should be set for the titles on these screens of around the dev bounds
- Yes un-internationalize FaceWithPointsNode (it makes no sense in our scoring if those point values are changed, and numbers themselves are international enough)
- The "try again"/"show answer" button max width should be set to not overlap with the rightmost measuring tray

**Comment by jbphet** [comment]
It is internationalized because someone might want the plus sign on the other side.  I'm pretty sure that there was a specific request for this from one of the other developers or a translator - it's unlikely that I would have thought of this on my own.  I'm okay with un-internationalizing it as @ariel-phet is recommending above - I just checked the Arabic translation for this file and they did *not* reverse it, so it must not be that important to them at least one translator for an RTL language.  See https://github.com/phetsims/babel/commit/7a3deb204d74a53bab86a49d49b917d5a172f2b7.

If it is un-internationalized, please remove it from all translated string files.

**Comment by ariel-phet** [comment]
when we have checked with RTL translator, math is still written LTR (this came up with graphing lines, since allowing a flexible layout with those dynamic equations would have been brutal).

So I would still say un-internationalize . Things like writing coordinates, using commas vs decimal points, etc vary from region to region but standard arithmetic operations appear to be pretty universal.

**Comment by samreid** [comment]
I created an issue about uninternationalizing FaceWithPointsNode and assigned to me.

**Comment by samreid** [comment]
FaceWithPointsNode has been de-internationalized in the related issue, at least enough to proceed with work in this issue.

**Comment by samreid** [comment]
Noting the remaining issues from https://github.com/phetsims/fraction-matcher/issues/90#issuecomment-192138674

- [ ] the "mixed numbers" level selection screen the title "Choose your level! Mixed Numbers" does not pass ?stringtest=double. Max width should be set for the titles on these screens of around the dev bounds
- [ ] The "try again"/"show answer" button max width should be set to not overlap with the rightmost measuring tray

**Comment by samreid** [comment]
This sim has a custom layout bounds:

```js
new Bounds2( 0, 0, 768, 504 )
```

Compare to the default:

```js
new Bounds2( 0, 0, 1024, 618 )
```

**Comment by samreid** [comment]
Fixed the level selection title width, I'll check it off.

**Comment by samreid** [comment]
Here's a pic of the remaining issue:

![image](https://cloud.githubusercontent.com/assets/679486/13669819/3e8cdaae-e683-11e5-97e7-e2d5dea42bcf.png)

**Comment by samreid** [comment]
All of the 4 button types here are TextPushButton, which doesn't support a text maxWidth.  Currently if we set the maxWidth it would change the size of the entire button, not just the text on the button.  I'm inclined to add a maxTextWidth option to TextPushButton, but I should get a +1 from another developer in case there is a better way to do this.

**Comment by samreid** [comment]
With maxTextWidth: 120 it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/13670081/e8920d5c-e684-11e5-895e-1da40446ec91.png)

**Comment by samreid** [comment]
Fixed above, @ariel-phet would you like to pull and verify?

**Comment by ariel-phet** [comment]
All looks good @samreid!

**Comment by samreid** [comment]
Thanks, we'll continue in #92
